"""Build the bundle, unpack it, and make it answer.

Run on every push rather than at a tag. A bundle assembles from a manifest generated by
one module and a dependency tree resolved by pip, and neither of those is exercised by the
test suite: the suite imports the package it is sitting next to. So the first time anybody
finds out that the bundle does not start is the release, by which point the tag is
permanent.

What is checked is what a client would notice. That it starts at all, that it speaks the
protocol, and that the tool list the manifest advertises before installation is the tool
list the server serves after it. The third is the one that goes wrong quietly: a manifest
promising a tool that is not there sends a model at a method that does not exist.

    python scripts/check_bundle.py
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from build_bundle import build  # noqa: E402


def ask(launcher: Path, *methods: str) -> list[dict]:
    """Put requests to the bundled server over stdio and read what comes back."""
    requests = "".join(
        json.dumps({"jsonrpc": "2.0", "id": n, "method": m, "params": {}}) + "\n"
        for n, m in enumerate(methods, start=1)
    )
    finished = subprocess.run(
        [sys.executable, str(launcher)],
        input=requests,
        capture_output=True,
        text=True,
        timeout=120,
    )
    if finished.returncode != 0:
        raise SystemExit(f"the bundled server exited {finished.returncode}:\n{finished.stderr}")
    return [json.loads(line) for line in finished.stdout.splitlines() if line.strip()]


def main() -> int:
    with tempfile.TemporaryDirectory() as workspace:
        here = Path(workspace)
        bundle = build(here / "gagelink.mcpb")
        print(f"built {bundle.name} ({bundle.stat().st_size // 1024} KiB)")

        with zipfile.ZipFile(bundle) as archive:
            names = archive.namelist()
            if names[0] != "manifest.json":
                raise SystemExit(f"manifest.json is not the first entry, {names[0]} is")
            declared = json.loads(archive.read("manifest.json"))
            archive.extractall(here / "unpacked")

        launcher = here / "unpacked" / declared["server"]["entry_point"]
        if not launcher.exists():
            raise SystemExit(f"the manifest names {launcher.name} and the bundle has no such file")

        answers = ask(launcher, "tools/list", "prompts/list", "resources/list")
        served = {
            "tools": [t["name"] for t in answers[0]["result"]["tools"]],
            "prompts": [p["name"] for p in answers[1]["result"]["prompts"]],
            "resources": [r["uri"] for r in answers[2]["result"]["resources"]],
        }

        for surface in ("tools", "prompts"):
            advertised = [entry["name"] for entry in declared[surface]]
            if advertised != served[surface]:
                raise SystemExit(
                    f"the manifest advertises {surface} {advertised} and the bundled "
                    f"server serves {served[surface]}"
                )

        if declared["version"] != _packaged_version(here / "unpacked"):
            raise SystemExit("the manifest version and the bundled package disagree")

        print(
            f"bundle serves {len(served['tools'])} tools, "
            f"{len(served['prompts'])} prompts, {len(served['resources'])} resources"
        )
    return 0


def _packaged_version(unpacked: Path) -> str:
    """The version of the package actually inside the bundle, read from what shipped.

    Read from the vendored copy rather than from the import that generated the manifest,
    which is the whole point: those are two different trees and a bundle built against a
    stale install would otherwise agree with itself.
    """
    source = (unpacked / "server" / "lib" / "gagelink" / "__init__.py").read_text()
    for line in source.splitlines():
        if line.startswith("__version__"):
            return line.split('"')[1]
    raise SystemExit("the bundled package declares no version")


if __name__ == "__main__":
    raise SystemExit(main())
